# Generated by Django 4.2.6 on 2023-10-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('ssn', models.CharField(max_length=9, primary_key=True, serialize=False)),
            ],
        ),
    ]
