# Generated by Django 4.2.6 on 2023-10-31 01:06

import UIHealthApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UIHealthApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(default='123 fake st', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='medicalHistory',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupationalClass',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='phoneNumber',
            field=models.CharField(default='1234567890', max_length=10, validators=[UIHealthApp.models.validate_length]),
        ),
    ]
