# Generated by Django 4.2.6 on 2023-11-01 23:31

import UIHealthApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UIHealthApp', '0002_patient_address_patient_age_patient_medicalhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('employeeID', models.CharField(default='123456789', max_length=9, primary_key=True, serialize=False, validators=[UIHealthApp.models.IDVarifier])),
                ('address', models.CharField(default='124 fake st', max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('phoneNumber', models.CharField(default='1234567890', max_length=10, validators=[UIHealthApp.models.validate_length])),
                ('gender', models.CharField(default='None', max_length=6)),
                ('name', models.CharField(default='None', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('vaccineID', models.CharField(default='123456789', max_length=9, primary_key=True, serialize=False, validators=[UIHealthApp.models.IDVarifier])),
                ('companyName', models.CharField(default='Fake Company', max_length=50)),
                ('name', models.CharField(default='vaccine', max_length=50)),
                ('doses', models.IntegerField(default=0)),
                ('availability', models.IntegerField(default=0)),
                ('onHold', models.IntegerField(default=0)),
                ('textDesc', models.CharField(default='None', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='None', max_length=6),
        ),
        migrations.AddField(
            model_name='patient',
            name='race',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.CreateModel(
            name='VaccinationScheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeSlot', models.DateField()),
                ('nurseID', models.ForeignKey(default='123456789', max_length=9, on_delete=django.db.models.deletion.SET_DEFAULT, to='UIHealthApp.nurse', validators=[UIHealthApp.models.IDVarifier])),
                ('patientID', models.ForeignKey(default='123456789', max_length=9, on_delete=django.db.models.deletion.SET_DEFAULT, to='UIHealthApp.patient', validators=[UIHealthApp.models.IDVarifier])),
                ('vaccineID', models.ForeignKey(default='123456789', max_length=9, on_delete=django.db.models.deletion.SET_DEFAULT, to='UIHealthApp.vaccine', validators=[UIHealthApp.models.IDVarifier])),
            ],
        ),
        migrations.CreateModel(
            name='vaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doses', models.IntegerField(default=0)),
                ('nurseID', models.ForeignKey(default='123456789', max_length=9, on_delete=django.db.models.deletion.SET_DEFAULT, to='UIHealthApp.nurse', validators=[UIHealthApp.models.IDVarifier])),
                ('patientID', models.ForeignKey(default='123456789', max_length=9, on_delete=django.db.models.deletion.SET_DEFAULT, to='UIHealthApp.patient', validators=[UIHealthApp.models.IDVarifier])),
                ('vaccineID', models.ForeignKey(default='123456789', max_length=9, on_delete=django.db.models.deletion.SET_DEFAULT, to='UIHealthApp.vaccine', validators=[UIHealthApp.models.IDVarifier])),
            ],
        ),
    ]
