# Generated by Django 4.2.6 on 2023-11-09 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UIHealthApp', '0003_nurse_vaccine_patient_gender_patient_race_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('password', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='nurse',
            name='username',
            field=models.ForeignKey(default='', max_length=10, on_delete=django.db.models.deletion.SET_DEFAULT, to='UIHealthApp.credentials'),
        ),
        migrations.AddField(
            model_name='patient',
            name='username',
            field=models.ForeignKey(default='', max_length=10, on_delete=django.db.models.deletion.SET_DEFAULT, to='UIHealthApp.credentials'),
        ),
    ]
