# Generated by Django 4.2.6 on 2023-11-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UIHealthApp', '0004_credentials_nurse_username_patient_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='username',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
    ]
