# Generated by Django 4.2.6 on 2023-11-09 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UIHealthApp', '0005_alter_credentials_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='username',
            field=models.CharField(default='default', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='username',
            field=models.ForeignKey(default='default', max_length=10, on_delete=django.db.models.deletion.SET_DEFAULT, to='UIHealthApp.credentials'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='username',
            field=models.ForeignKey(default='default', max_length=10, on_delete=django.db.models.deletion.SET_DEFAULT, to='UIHealthApp.credentials'),
        ),
    ]
