# Generated by Django 4.2.7 on 2023-11-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UIHealthApp', '0006_alter_credentials_username_alter_nurse_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vaccinationscheduling',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
