# Generated by Django 4.2.7 on 2023-11-19 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UIHealthApp', '0007_patient_name_alter_vaccinationrecord_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccinationscheduling',
            name='vaccineID',
        ),
    ]
