# Generated by Django 4.2.7 on 2023-11-20 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UIHealthApp', '0008_remove_vaccinationscheduling_vaccineid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinationrecord',
            old_name='id',
            new_name='recordID',
        ),
        migrations.RenameField(
            model_name='vaccinationscheduling',
            old_name='id',
            new_name='vaccID',
        ),
    ]
