# Generated by Django 4.2.7 on 2023-11-20 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UIHealthApp', '0010_alter_vaccinationrecord_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationscheduling',
            name='patientID',
            field=models.ForeignKey(default='123456789', max_length=9, on_delete=django.db.models.deletion.SET_DEFAULT, to='UIHealthApp.patient'),
        ),
    ]
