# Generated by Django 4.2.7 on 2023-11-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UIHealthApp', '0012_alter_vaccinationrecord_nurseid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationscheduling',
            name='timeSlot',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
