# Generated by Django 4.2.7 on 2023-11-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UIHealthApp', '0013_alter_vaccinationscheduling_timeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='timeSlot',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
